global:
  dist-dirs: &distDirs dist
  tsconfig: tsconfig.json

copy-files:
  from:
  - package.json
  - LICENSE
  - CHANGELOG.md
  - README.md
  to: *distDirs

build:
  entry: src/index.ts
  license-banner: true
  out: *distDirs
  umd-name: LocalforageDriverMemory
  externals: &ext
  - tslib
  - localforage-driver-commons
  ignore-umd-externals: *ext
